wso2/wso2-wss4j

modules/wss4j/pom.xml, modules/wss4j/src/org/apache/ws/security/kerberos/KrbTicketDecoder.java
=> Changes for Java 8

modules/wss4j/pom.xml, modules/wss4j/src/org/apache/ws/security/kerberos/KrbTicketDecoder.java
Reverts wso2/wso2-wss4j#10 . Will merge once again once jenkins is ready and products are ready to release in 1.8.
=> Revert "Changes for Java 8".

modules/orbit/pom.xml, modules/wss4j/pom.xml, modules/wss4j/src/org/apache/ws/security/kerberos/KrbTicketDecoder.java, pom.xml
=> Revert "Release 1.5.11 wso2v10"

modules/orbit/pom.xml, modules/wss4j/pom.xml, pom.xml
Reverts wso2/wso2-wss4j#24 because of jdk 8 failures
=> Reverting "Fixes for IDENTITY-3726 and IDENTITY-3723"

modules/orbit/pom.xml, modules/wss4j/pom.xml, pom.xml
Also re-adding fix in #24 after fixing the java 8 issues
=> Fix for IDENTITY-4438

modules/wss4j/test/components/TestReference.java
reverted commit 9d4297be10e7f20e1b62e0d5e001d0871c7a6ad7 in Test case
=> Revert the use of secured document builder in the Test case

modules/wss4j/pom.xml, pom.xml
>Purpose of this PR is to add jacoco plugin integration to the repository for code coverage purposes.
=> Jacoco plugin integration

README.md
=> Update jenkins job url

modules/wss4j/pom.xml, pom.xml
=> Add missing plugin versions

modules/wss4j/pom.xml, pom.xml
=> Update assembly plugin version

modules/orbit/pom.xml, modules/wss4j/pom.xml, pom.xml
=> Change the versions incremented by Jenkins back to wso2

pom.xml
=> Update exp pkg and import pkg range

pom.xml
Failed PMD validation after version bump.
Reverting the bump version
=> reverted PMD plugin bump to fix test failures

modules/orbit/pom.xml, pom.xml
- Remove embedded OpenSAML2 dependencies to fix ws-trust scenarios.
=> Remove embedded OpenSAML2 dependencies.

modules/wss4j/src/org/apache/ws/security/processor/SAML2TokenProcessor.java
Fix: https://github.com/wso2/product-ei/issues/5545
=> Fix issue of initializing saml library for each assertion

modules/wss4j/src/org/apache/ws/security/processor/SAML2TokenProcessor.java
=> Add correct exception

modules/orbit/pom.xml, modules/wss4j/pom.xml, modules/wss4j/src/org/apache/ws/security/processor/KerberosTokenProcessor.java, modules/wss4j/src/org/apache/ws/security/processor/SignatureProcessor.java, pom.xml
> Add xmlsec orbit dependency
Enable secureValidation in required places
=> Add xmlsec orbit dependency

modules/wss4j/pom.xml, modules/wss4j/test/wssec/PackageTests.java, pom.xml
This is to fix unit tests failures
1. Upgrade bouncycastle version
2. Saml based testcases will be removed as there is no usecases currently
> Brief description of the new feature or bug fix as it will appear in the …
=> Upgrade bouncycastle version

pom.xml
=> Change repo URLs to https in pom.xml files

pom.xml
=> Add nexus release repository

.github/workflows/push_ubuntu_build.yml, modules/wss4j/pom.xml, pom.xml
> $Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Generate code coverage

pom.xml
Upgrade slf4j version to 2.0.12
=> Upgrade slf4j version to 2.0.12
